### PR TITLE
3.x

### PR DESCRIPTION
**Pull request by saade**
v3 is out! This PR was closed due to the `main` branch deletion.

### CODE REVIEW

**Comment by chengkangzai** [comment]
i dont want to sound pushing ... 
but do we have a timeline for this package to support filament v3 ? 
or any blockage of this PR that communities can help? 

Thanks for your work!

**Comment by saade** [comment]
hey @chengkangzai,

currently the plugin already works in v3, the latest version that supports v3 is [v3.0.0-beta3](https://github.com/saade/filament-fullcalendar/releases/tag/v3.0.0-beta3)

i do have some refactor (and breaking changes) to do before i can tag v3, i don't want to tag v3 right now and break someone's app later with the BCs

**Comment by chengkangzai** [comment]
Alright, I will test it out and let you know if it have any problems 🤘

Thanks again @saade 🙏

**Comment by Sh1d0w** [comment]
> hey @chengkangzai,
> 
> currently the plugin already works in v3, the latest version that supports v3 is [v3.0.0-beta3](https://github.com/saade/filament-fullcalendar/releases/tag/v3.0.0-beta3)
> 
> i do have some refactor (and breaking changes) to do before i can tag v3, i don't want to tag v3 right now and break someone's app later with the BCs

Thanks, but it does not seem to work

```
 Problem 1
    - Root composer.json requires saade/filament-fullcalendar 3.0.0-beta3 -> satisfiable by saade/filament-fullcalendar[v3.0.0-beta3].
    - saade/filament-fullcalendar v3.0.0-beta3 requires filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.53] but it conflicts with your root composer.json require (^3.0).
```

**Comment by saade** [comment]
> Thanks, but it does not seem to work
> 
> ```
>  Problem 1
>     - Root composer.json requires saade/filament-fullcalendar 3.0.0-beta3 -> satisfiable by saade/filament-fullcalendar[v3.0.0-beta3].
>     - saade/filament-fullcalendar v3.0.0-beta3 requires filament/filament ^2.0 -> found filament/filament[v2.5.3, ..., v2.17.53] but it conflicts with your root composer.json require (^3.0).
> ```

Weird, i'm requiring [^3.0](https://github.com/saade/filament-fullcalendar/pull/100/files#:~:text=%22filament/filament%22%3A%20%22%5E3.0%22%2C)

**Comment by Sh1d0w** [comment]
@saade According to GitHub releases the 3.0.0-beta3 tag is published to composer from this commit https://github.com/saade/filament-fullcalendar/tree/7f4a801ee40eec4db2004ed913c4e8dcfc68b54f

Which is the main branch. The 3 tag should be published from the 3.x branch instead. I will install the package directly from GitHub branch, but just to let you know in future that the current tag is still pointing to the main branch where it has filament 2 support.

**Comment by saade** [comment]
> @saade According to GitHub releases the 3.0.0-beta3 tag is published to composer from this commit https://github.com/saade/filament-fullcalendar/tree/7f4a801ee40eec4db2004ed913c4e8dcfc68b54f
> 
> Which is the main branch. The 3 tag should be published from the 3.x branch instead. I will install the package directly from GitHub branch, but just to let you know in future that the current tag is still pointing to the main branch where it has filament 2 support.

🤦🏼 i've target the wrong branch, sorry about that [v3.0.0-beta4](https://github.com/saade/filament-fullcalendar/releases/tag/v3.0.0-beta4) is out

**Comment by chengkangzai** [comment]
Aite the full plugin work perfectly in my upgrade to filament v3 👍  

Good job! Thanks Saade once again

**Comment by chengkangzai** [comment]
I apologies, just realise there is error in browser's console log. Attached with the console log.
But the plugin still shows tho

Screenshot 2023-09-24 at 11 23 20 AM
Screenshot 2023-09-24 at 11 23 28 AM
Screenshot 2023-09-24 at 11 26 49 AM

**Comment by saade** [comment]
👀 only documentation left

**Comment by saade** [comment]
V3 is out! this PR was closed due to `main` branch deletion

**Pull request closed without merging**
