### PR TITLE
Allow event's model to have relationship

### LINKED ISSUE #43: Using event form with relations
I am not able to make it working with an event form using relations : a select or  repeater.
Simple form :
```php
protected static function getCreateEventFormSchema(): array
    {
        return [
            Forms\Components\Select::make('planning_id')
                ->label(__('Planning'))
                ->validationAttribute(__('Planning'))
                ->searchable()
                ->relationship('planning', 'name')
                ->preload()
                ->required(),
            Forms\Components\DatePicker::make('start_at')
                ->required(),
            Forms\Components\DatePicker::make('end_at')
                ->default(null),
        ];
    }
```

I got : Call to a member function planning() on null
Event if the relation exists

### PR DESCRIPTION
**Pull request by tiagof**
Attempt to fix #43

### CODE REVIEW

**Comment by saade** [comment]
@invaders-xx can u test and see if this works for you? thanks

**Comment by invaders-xx** [comment]
@saade, how do I test it ? I am not a github expert ;-)

**Review by saade — APPROVED** [review]

**Comment by saade** [comment]
Hi @tiagof, it seems that this does not work for people that does not use a model to represent event. (like me).

I've reverted that since i do not have time to debug this myself, feel free to reopen this with the fix.

**Comment by tiagof** [comment]
Hi @saade, happy to look into it if you/someone provides the bug report.
Cheers

**Pull request merged**
