### PR TITLE
Add support for writing custom JS to interact with FullCalendar's render hooks

### PR DESCRIPTION
**Pull request by cawecoy**
Possibility to use the [`eventDidMount` Event Render Hook](https://fullcalendar.io/docs/event-render-hooks):

```
return $painel->plugins([
    FilamentFullCalendarPlugin::make()->eventDidMount('calendarEventTooltip')
]);
```

In the example above we are adding a callback to my `calendarEventTooltip` Javascript function on the FullCalendar eventDidMount Event Render Hook parameter. The result:

```
const calendar = new Calendar(this.$el, {
    //...
    eventDidMount: calendarEventTooltip
});
```

[The FullCalendar documentation](https://fullcalendar.io/docs/event-render-hooks) says:

> Customize the rendering of event elements with the following options:
> 
> (...)
>
> `eventDidMount` - called right after the element has been added to the DOM. If the event data changes, this is NOT called again.

FullCalendar even has [a demo with sourcecode editable in CodePen on how to use `eventDidMount` to easily create an event Tooltip](https://fullcalendar.io/docs/event-tooltip-demo).

Similar feature was requested twice on saade/filament-fullcalendar: https://github.com/saade/filament-fullcalendar/issues/162 and https://github.com/saade/filament-fullcalendar/discussions/135.

Currently, one might think we could use the [config(`array` $config) method](https://github.com/saade/filament-fullcalendar?tab=readme-ov-file#configarray-config):

```
return $painel->plugins([
    FilamentFullCalendarPlugin::make()->config(['eventDidMount' => 'calendarEventTooltip'])
]);
```

But it has a problem: the callback function is rendered as string (surrounded by quotes).

```
const calendar = new Calendar(this.$el, {
    //...
    eventDidMount: 'calendarEventTooltip'
});
```

That generates the following error: `Uncaught SyntaxError: Invalid or unexpected token`.

### In summary, it's currently not possible to use the FullCalendar `eventDidMount` through this Filament Plugin and this PR will fix that.

# Test: implementing the event tooltip on hover

Following the given example exposed before... 

```
return $painel->plugins([
    FilamentFullCalendarPlugin::make()->eventDidMount('calendarEventTooltip')
]);
```

...additionaly, we just need to add the following Javascript code to our Filament page:

```
<script>
    function calendarEventTooltip(info){
        info.el.setAttribute("x-tooltip", "tooltip"); // see the tooltip options: https://github.com/ryangjchandler/alpine-tooltip?tab=readme-ov-file#modifiers
        info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }"); // we can use info.event.description or anything else sent on the Calendar Widget's fetchEvents method
    }
</script>
```

And we are done (this example uses the [Alpine Tooltip](https://github.com/ryangjchandler/alpine-tooltip?tab=readme-ov-file#modifiers) package that comes already installed with Filament by default).

image

### CODE REVIEW

**Comment by cawecoy** [comment]
Hi @saade! Is there any chance of this PR being accepted? Thx!

**Comment by saade** [comment]
I'm thinking on another aproach, what about adding a method `eventDidMount` on the calendar class, and use like this:

```php
public function eventDidMount(info) {
    return <<<JS
        info.el.setAttribute("x-tooltip", "tooltip");
        info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }");
    JS;
}
```

thoughts?

**Comment by cawecoy** [comment]
@saade it looks like a great approach. But how will the user customize it? What is the "calendar class" exactly?

**Comment by saade** [comment]
> @saade it looks like a great approach. But how will the user customize it? What is the "calendar class" exactly?

the default definition for the function will be:

```php
public function eventDidMount(info) {
    //
}
```

then the user can override this method in their own widget class that extends the FullCalendarWidget

```php
public function eventDidMount(info) {
    // this is the custom js wrote by the user while overriding the default method
    return <<<JS
        info.el.setAttribute("x-tooltip", "tooltip");
        info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }");
    JS;
}
```

**Comment by cawecoy** [comment]
@saade ok. Another questions:

1. What is the "calendar class" exactly?
2. Is your your `eventDidMount` method a PHP or JavaScript method? I guess it's JavaScript and you used `public` by mistake?

**Comment by cawecoy** [comment]
Oh no, it's PHP because of the `<<<JS`. But you missed $ in the parameter: `public function eventDidMount($info)`

How would we make `$info` accessible via JavaScript `info.event.title`?

**Comment by saade** [comment]
> @saade ok. Another questions:
> 
> 1. What is the "calendar class" exactly?
> 2. Is your your `eventDidMount` method a PHP or JavaScript method? I guess it's JavaScript and you used `public` by mistake?

1.

```php
<?php

namespace App\Filament\Widgets;

use Saade\FilamentFullCalendar\Widgets\FullCalendarWidget;

class CalendarWidget extends FullCalendarWidget
{
    // ....
    
    public function eventDidMount(info) {
        return <<<JS
            info.el.setAttribute("x-tooltip", "tooltip");
            info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }");
        JS;
    }
    
   // ....
}
```

2. `eventDidMount` is a method inside the above class. In the js side you just:

```js
eventDidMount: function (info) {
   this.$wire.eventDidMount(info);
} 
```

**Comment by cawecoy** [comment]
> > @saade ok. Another questions:
> > 
> > 1. What is the "calendar class" exactly?
> > 2. Is your your `eventDidMount` method a PHP or JavaScript method? I guess it's JavaScript and you used `public` by mistake?
> 
> 
> ```
> <?php
> 
> namespace App\Filament\Widgets;
> 
> use Saade\FilamentFullCalendar\Widgets\FullCalendarWidget;
> 
> class CalendarWidget extends FullCalendarWidget
> {
>     // ....
>     
>     public function eventDidMount(info) {
>         return <<<JS
>             info.el.setAttribute("x-tooltip", "tooltip");
>             info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }");
>         JS;
>     }
>     
>    // ....
> }
> ```
> 
> 2. `eventDidMount` is a method inside the above class. In the js side you just:
> 
> ```js
> eventDidMount: function (info) {
>    this.$wire.eventDidMount(info);
> } 
> ```

I've tried that, but it's not working somehow... the events are not displayed. No errors on the browser console log. Any ideas?

**Comment by saade** [comment]
oh shoot, yes i see why, its something along those lines, but i've expressed myself wrong while writing the snippet. Give me a couple of minutes and i i'll try to implement it

**Comment by cawecoy** [comment]
Hi @saade! Do you have any update on this?

**Comment by cawecoy** [comment]
Hi @saade! Do you have any update?

**Comment by cawecoy** [comment]
@saade I finally got to make it work through the approach you suggested:

```php
public function eventDidMount() {
    return <<<JS
        function calendarEventTooltip(info){
            info.el.setAttribute("x-tooltip", "tooltip");
            info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }");
        }
    JS;
}
```

How about that?

**Comment by cawecoy** [comment]
@saade I finally got to make it work through the approach you suggested:

```php
public function eventDidMount() {
    return <<<JS
        function (info){
            info.el.setAttribute("x-tooltip", "tooltip");
            info.el.setAttribute("x-data", "{ tooltip: '"+info.event.title+"' }");
        }
    JS;
}
```

How about that?

**Comment by KhairulAzmi21** [comment]
I need this PR :)

**Comment by KhairulAzmi21** [comment]
@cawecoy . do you have any idea how to styling the tooltip ?

**Comment by cawecoy** [comment]
> I need this PR :)

@KhairulAzmi21 me too. Sometimes the full event content does not fit in the small event container on the calendar - it often ends up partially hidden. So the Tooltip would provide a great UX here by allowing the user to easily see the full event content just by hovering the event.

I am waiting for the maintainer @saade to review my PR (:

> @cawecoy . do you have any idea how to styling the tooltip ?

I style it throught this CSS code:

```CSS
.tippy-box[data-theme~=light]{
    background-color: rgb(var(--gray-700)) !important;
    color: rgb(255 255 255);
}
.tippy-box[data-theme~=light][data-placement^=top]>.tippy-arrow:before{
    border-top-color: rgb(var(--gray-700)) !important;
}
.tippy-box[data-theme~=light][data-placement^=right]>.tippy-arrow:before{
    border-right-color: rgb(var(--gray-700)) !important;
}
.tippy-box[data-theme~=light][data-placement^=bottom]>.tippy-arrow:before{
    border-bottom-color: rgb(var(--gray-700)) !important;
}
.tippy-box[data-theme~=light][data-placement^=left]>.tippy-arrow:before{
    border-left-color: rgb(var(--gray-700)) !important;
}
```

FilamentPHP uses Tippy.js. I've found that CSS on its official website: https://atomiks.github.io/tippyjs/v6/themes/

**Comment by saade** [comment]
@cawecoy could you test to see if its still working as desired?

**Comment by saade** [comment]
@cawecoy? :)

**Comment by cawecoy** [comment]
> @cawecoy could you test to see if its still working as desired?

@saade sure! I'm testing it now (:

**Comment by cawecoy** [comment]
@saade I just tried all the Event Render Hooks (except `eventWillUnmount`), they are working as expected. 

`eventWillUnmount` is called right before the event will be removed from the DOM. Any idea on how to remove an event via fullcalendar in order to test it?

**Comment by saade** [comment]
@cawecoy i think paginating through the months of the calendar will fire it. Since eventDidMount is fired under the same condition

**Comment by cawecoy** [comment]
> @cawecoy i think paginating through the months of the calendar will fire it. Since eventDidMount is fired under the same condition

Great idea! It works!

**Comment by saade** [comment]
Cool, thank you for your contribution!

**Comment by CharlieEtienne** [comment]
Hi @cawecoy , thank you for that! 

Any idea on how to write HTML in tooltips ?

Thanks,

**Pull request merged**
