### PR TITLE
Fix/fetch events cache

### LINKED ISSUE #22: Problem with  `cachedEventIds` in the `fetchEvents` function
I am getting events disappearing when I use the `fetchEvents()` method to load calendar events.

If I comment out the line the caches the event ids in the `fullcalendar.blade.php` file, it works as expected.

```js
const fetchEvents = function ({ start, end }, successCallback, failureCallback) {
    @if( $this::canFetchEvents() )
        return $wire.fetchEvents({ start, end }, cachedEventIds)
            .then(events => {
                // Cache fetched events
                //cachedEventIds.push(...events.map(event => event.id)); <--- comment out this line fixes the issue

                return successCallback(events);
            })
            .catch( failureCallback );
    @else
        return successCallback([]);
    @endif
}
```

I think this is due to the way Fullcalendar calls Event Sources that are a function.

From the Fullcalendar docs:

> events (as a function) 
> ...
> FullCalendar will call this function whenever it needs new event data. This is triggered when the user clicks prev/next or switches views.

Is this line needed? I am not getting any duplication of events if it is commented out.

### PR DESCRIPTION
**Pull request by wychoong**
fixes #22

### CODE REVIEW

**Comment by ashleyhood** [comment]
I have tried this fix but it only works if you don't use both `public function getViewData()` and `public function fetchEvents(array $fetchInfo, array $ignorableIds)`. This is because the events will now be duplicated from both methods. 

If we keep the ignored ids for only events added from `getViewData()` we can have the initial events loaded with the widget and then use `fetchEvents` method to populate events when _next_ or _prev_ button clicked. We will still need to filter out the _$ignorableIds_ in the `fetchEvents` method.

```js
const cachedEventIds = [
    ...events.map(event => event.id),
];
...
return $wire.fetchEvents({ start, end, allDay }, cachedEventIds)
...
```

**Comment by wychoong** [comment]
Should the functions used exclusively to each other? By using both will have duplicate codes imo.

**Comment by ashleyhood** [comment]
So the documentation should say to use just one of the methods and never both (as it says you can use both in the docs at the moment).

I'm happy with that.

**Comment by ashleyhood** [comment]
You will also need to update the commented out method in the `trait CanFetchEvents` concern.

**Comment by saade** [comment]
Thanks for the debugging around this guys!

> So the documentation should say to use just one of the methods and never both (as it says you can use both in the docs at the moment).
> 
> I'm happy with that.

Gonna update the readme and the concern. Thanks!

**Pull request merged**
