### PR TITLE
Fix/store record id for edit

### PR DESCRIPTION
**Pull request by wychoong**
currently there is no way to retrieve the id or record, with this PR, you can do this

```php

    public function resolveEventRecord(array $data): Model
    {
        return Appointment::find($data['id']);  // or slug return Appointment::where('slug', $data['extendedProps']['slug']); <- the $data structure not tested
    }

    public function editEvent(array $data): void
    {
        $this->record->update($data);
        $this->refreshEvents();
    }

```

### CODE REVIEW

**Comment by wychoong** [comment]
> I dont plan to include any database related stuff into this lib. The ID should be received in `$data`.

It won’t be in $data if there is no id field in the form. Don’t think that’s the right way of passing id thou, it will be modifiable by user.

**Comment by saade** [comment]
you are correct. ill take a look at this tomorrow

**Comment by ashleyhood** [comment]
For what it is worth, I think this would be helpful. I solve this at the moment by having to store the `id` on the widget when `onEventClick` or `onEventDrop` method is called and then having to retrieve the `id` in the `editEvent` method.

**Comment by saade** [comment]
@wychoong do you mind writing the docs for this?

also, please resolve the conflicts and we are good to merge this =)

**Comment by wychoong** [comment]
> @wychoong do you mind writing the docs for this?
> 
> also, please resolve the conflicts and we are good to merge this =)

sorry for the late, was taking few days off due to covid

**Comment by dbrnjh47** [comment]
Similar problem, I asked this question and also there is an outcome to solve the problem

https://github.com/filamentphp/filament/issues/13198

**Comment by wychoong** [comment]
> Similar problem, I asked this question and also there is an outcome to solve the problem
> 
> [filamentphp/filament#13198](https://github.com/filamentphp/filament/issues/13198)

I don’t see how is that relevant. Please use the right channel for your issue.

**Pull request merged**
